### ISSUE TITLE
Original file corrupted after using this software with -p parameter

### ISSUE THREAD

**Issue by Lukasss93** [RobyFerro/Resume-Parser-CLI#1]
**Original file corrupted after using this software with -p parameter**

Exception:
```
(node:2253) UnhandledPromiseRejectionWarning: Error: Error extracting PDF text for file at [[ Curriculum.pdf ]], error: pdf-text-extract command failed: Syntax Warning: May not be a PDF file (continuing anyway)
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't read xref table

    at /usr/local/lib/node_modules/resume-parser-cli/node_modules/textract/lib/extractors/pdf.js:14:15
    at splitPages (/usr/local/lib/node_modules/resume-parser-cli/node_modules/pdf-text-extract/index.js:60:14)
    at ChildProcess.closeHandler (/usr/local/lib/node_modules/resume-parser-cli/node_modules/pdf-text-extract/index.js:104:14)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:606:12)
(node:2253) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2253) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by RobyFerro** [comment]
Fixed in 1.0.0-Beta.20180913-2. Thank you!
